# This script should install comma and snark for you

# If there's an error, exit.
set -e

mkdir -p ~/src
mkdir -p ~/build/comma
mkdir -p ~/build/snark

###### First, comma ######
# https://github.com/acfr/comma/wiki/more-details-on-building-from-source
sudo apt-get install -y build-essential git cmake-curses-gui cmake perl python libboost-all-dev socat

# if you plan to use python modules and applications
sudo apt-get install -y python-dev python-numpy

cd ~/src/
git clone https://github.com/acfr/comma.git
cd ~/build/comma
# ccmake ~/src/comma
cmake -D BUILD_PYTHON_PACKAGES=ON ~/src/comma &&  make -j 4 && sudo make install

# exit
###### Then, snark ######
# https://github.com/acfr/snark/wiki/Snark-for-dummies,-on-ubuntu-debian
sudo apt-get install -y libeigen3-dev
sudo apt-get install -y libtbb-dev
sudo apt-get install -y zlib1g-dev libbz2-dev

# Install OpenCV by building 3.4.10 from source (4.2.0 is not supported).
sudo apt-get install -y libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
#  sudo apt-get install libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
# cd ~/src/
# git clone https://github.com/opencv/opencv/ --branch 3.4.11
# cd opencv
# mkdir build
# cd build
# cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
# make -j4
# sudo make install


# If 4.2.0 were supported, this would be fine:
# sudo apt-get install -y libopencv-dev libopencv-highgui-dev

# sudo add-apt-repository -y ppa:rock-core/qt4
# sudo apt-get update
sudo apt-get install -y libqt4-dev
# sudo apt-get install -y qtbase5-dev qt5-default qt3d5-dev libassimp-dev  qtdeclarative5-dev

cd ~/src/
git clone https://github.com/acfr/qt3d.git
cd qt3d
sudo /usr/share/qt4/bin/qmake ~/src/qt3d/qt3d.pro
sudo mkdir /usr/include/qt4/Qt3D
sudo mkdir /usr/include/qt4/Qt3DQuick
#  I had to edit a file in 3rdparty to make this build;
#    in 3rdparty/assimp/code/ObjFileParser.cpp, change line 267 to say "*pPtr" instead of "pPtr"
sudo make -j 4

# Dodgy fix for libboost issue as per https://github.com/acfr/snark/issues/131
# sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_regex.so /usr/lib/x86_64-linux-gnu/libBoost::regex.so

cd ~/src/
git clone https://github.com/acfr/snark.git
cd ~/build/snark
# ccmake ~/src/snark
# cmake . && make -j 4 && sudo make install
# Note: snark seems to be broken with OpenCV 4.2; so, turn off snark_build_imaging.
# Otherwise, you can keep most settings as autogenerated, though there are a few you can safely turn off. 
cmake ~/src/snark/ && make -j 4 && sudo make install
# -D snark_build_geodesy_solar=ON

# And then my dependencies!!
sudo apt install -y default-jre
